# Generated by Django 5.2.7 on 2025-10-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='f_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='l_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
