# Generated by Django 5.2.7 on 2025-11-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0002_rename_f_name_guest_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='content',
            field=models.TextField(default='NULL', verbose_name='Additional Message'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='firstname',
            field=models.CharField(max_length=15, verbose_name='enter your name'),
        ),
        migrations.AddField(
            model_name='guest',
            name='dropdown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.category'),
            preserve_default=False,
        ),
    ]
