# Generated by Django 5.2.7 on 2025-11-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0003_category_guest_content_alter_guest_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='content',
            field=models.TextField(blank=True, verbose_name='Additional Message'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dropdown',
            field=models.ForeignKey(default='Select Your Issue', on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='firstname',
            field=models.CharField(max_length=15),
        ),
    ]
